In [1]:
import random

n=10
k=10

elements = list(range(n))
elements

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
import numpy as np

def echantillon(n):
    elements = list(range(n))
    tirage1 = random.choices(elements, k=n)
    return np.unique(tirage1).tolist()
    

In [44]:
list_ = []
for _ in range(5):
    ids = echantillon(50)
    list_ += ids

np.unique(list_).shape

(49,)

In [45]:
tab = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [49]:
tab[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [52]:
ids = [0,2]
tab2 = np.array([ tab[:,id] for id in ids ])

In [53]:
tab2

array([[1, 4, 7],
       [3, 6, 9]])

In [6]:
!pip install kahypar

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 487.5 kB/s eta 0:00:0000:0100:01


In [11]:
from utils.ClusterEnsembles.ClusterEnsembles import mcla


label1 = np.array([1, 1, 1, 2, 2, 3, 3])

label2 = np.array([2, 2, 2, 3, 3, 1, 1])

label3 = np.array([4, 4, 2, 2, 3, 3, 3])

label4 = np.array([1, 2, np.nan, 1, 2, np.nan, np.nan]) # `np.nan`: missing value

labels = np.array([label1, label2, label3, label4])

mcla(labels,2,0)

array([1, 1, 1, 0, 0, 0, 0])

In [1]:
from datasets.load import load_msrcv1

dataset = load_msrcv1("datasets/")

In [5]:
dataset["X"][0].shape

(24, 210)

In [2]:
from bagging import bagging_prime

r = bagging_prime(dataset["X"], 7)

/home/mbe/Bureau/theme/memoire/workflows/bagging.py:43: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if typeweak is "mcles":
/home/mbe/anaconda3/lib/python3.10/site-packages/qpsolvers/conversions/ensure_sparse_matrices.py:38: UserWarning: Converted P to scipy.sparse.csc.csc_matrix
For best performance, build P as a scipy.sparse.csc_matrix rather than as a numpy.ndarray
  warnings.warn(
/home/mbe/anaconda3/lib/python3.10/site-packages/qpsolvers/conversions/ensure_sparse_matrices.py:38: UserWarning: Converted A to scipy.sparse.csc.csc_matrix
For best performance, build A as a scipy.sparse.csc_matrix rather than as a numpy.ndarray
  warnings.warn(
/home/mbe/Bureau/theme/memoire/workflows/bagging.py:43: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if typeweak is "mcles":
/home/mbe/Bureau/theme/memoire/workflows/bagging.py:43: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if typeweak is "mcles":


IndexError: list index out of range